config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  resources :chatrooms
  resources :messages
  # Root redirect
  root "welcome#index"

  # Clearance route overrides
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # Omniauth redirect
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

	# Resources from rails build
	resources :listing_photos
	resources :avatars
	resources :bookings
	resources :listings
	resources :users
  # resources :taggings NO NEEED RESOURCES TAGGING (NO TAGGING SHIT HAPPENING)
  # resources :tags NO NEED RESOURCES TAGS (NO TAG SHIT HAPPENING)

  # Manual additions
  # update user
  # make path for post to update
  patch "/users/:id" => "users#update", as: "update_user"

  # Verifying Listings
  put "/listings/verify/:id" => "listings#verify", as: "verify_listing"

  # Payments
  get '/payments/:booking_id' => "braintree#show", as: "payments"
  post 'braintree/checkout'

  # Guests
  get '/users/:id/guests' => "users#guests", as: "guests"

  #Searches
  # Filter search
  get '/search/show'

  # Text search
  get '/search/text_search'
  get '/search/text_search_ajax'

  # Mount channels for ActionCable
  mount ActionCable.server, at: '/cable'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  # Validations
  validates :first_name, :last_name, presence: true

  # Enum for roles
  enum role: [:customer, :moderator, :superadmin]

  # Associations
  has_many :authentications, dependent: :destroy #omniauth
  has_many 	:listings
  has_many 	:bookings
  has_one 	:avatar
  has_many :messages
  has_many :subscriptions
  has_many :chatrooms, through: :subscriptions

  # Symbols Constant (for ASCII)
  SYMBOLS = {login: "🚪", logout: "⏻"}

  # Functions
  def full_name # Returns full name
  	return "#{first_name} #{last_name}"
  end

  def average_rating
    result = 0
    divisor = 1

    if(listings.length > 0)
      listings.each do |listing|
        result += listing.rating
      end
      divisor = listings.length
    end

    return result/divisor
  end

  #Omniauth Functions
  def self.create_with_auth_and_hash(authentication, auth_hash)
    first_name = auth_hash["info"]["name"].split(" ").first
    last_name = auth_hash["info"]["name"].split(" ").last
    user = self.create!(
    first_name: first_name,
    last_name: last_name,
    email: auth_hash["info"]["email"],
    password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end

  # grab google to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :guests]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(first_name: user_params[:first_name], last_name: user_params[:last_name], email: user_params[:email], password: user_params[:password])

    respond_to do |format|
      if @user.save

        if(user_params[:avatar_image] != nil)
          new_avatar = @user.avatar.build(avatar_image: user_params[:avatar_image])
          new_avatar.save
        end

        sign_in(@user)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to new_user_path, notice: @user.errors.full_messages.join(". ") }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.email = user_params[:email]
    @user.first_name = user_params[:first_name]
    @user.last_name = user_params[:last_name]

    # Avatar updating / creating
    # Destroy the old avatar (if it exists) and make a new one
    if(@user.avatar != nil)
      @user.avatar.destroy
    end

    if(user_params[:avatar_image] != nil)
      new_avatar = @user.avatar.build(avatar_image: user_params[:avatar_image])
      new_avatar.save
    end


    if(@user.save)
      flash[:success] = "Successfully updated profile!"
      redirect_to user_path(@user.id)
    else
      flash[:error] = "Failed to update profile!"
      redirect_to user_path(@user.id)
    end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Account successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def guests
    @user_all_listings = @user.listings
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar_image)
    end
end

app/helpers/users_helper.rb
module UsersHelper

	def current_user_is(user)
		(current_user.id == user.id)? true : false
	end


	def show_role
		if (signed_in?)

			case current_user.role

			when "superadmin"
				return content_tag :h2, :class => "red" do
					"Logged in as superadmin!"
				end

			when "moderator"
				return content_tag :h2, :class => "blue" do
					"Logged in as moderator!"
				end
			else
				return ""
			end
	
		else
			return ""
		end
	end

end

app/views/users/_edit_user_form.erb
<div class="container px-3 py-2">
	<%= form_for :user, url: user_path(user.id), method: :patch do |f| %>
	<div class="form-row mb-2">
		<div class="col input-group">
			<div class="input-group-prepend" data-toggle="tooltip" title="First Name" data-placement="left" >
				<div class="input-group-text">
					<i class="fas fa-signature"></i>		
				</div>
			</div>
			<%= f.text_field :first_name, :class => "form-control", :placeholder => "First Name" %>
		</div>
	</div>

	<div class="form-row mb-2">
		<div class="col input-group">
			<div class="input-group-prepend" data-toggle="tooltip" title="Last Name" data-placement="left" >
				<div class="input-group-text">
					<i class="fas fa-signature"></i>		
				</div>
			</div>
			<%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name" %>
		</div>
	</div>

	<div class="form-row mb-2">
		<div class="col input-group">
			<div class="input-group-prepend" data-toggle="tooltip" title="Email Address" data-placement="left" >
				<div class="input-group-text">
					<i class="fas fa-at"></i>
				</div>
			</div>
			<%= f.text_field :email, :class => "form-control", :placeholder => "Email Address" %>
		</div>
	</div>

	<div class="form-row mb-2">
		<div class="col input-group">
			<div class="input-group-prepend" data-toggle="tooltip" title="Avatar Image (optional)" data-placement="left" >
				<div class="input-group-text">
					<i class="fas fa-image"></i>
				</div>
			</div>
			<%= f.file_field :avatar_image, :class => "form-control" %>
		</div>
	</div>
					
			
			<%= f.submit "Submit", :class => "btn btn-primary w-100 mb-2"%>
			<%= link_to 'Back to Profile', user_path(@user.id), :class => "btn btn-secondary w-100 mb-2" %>
	<% end %>
</div>

app/views/users/_form.erb
<%= form_for :user, url: new_user_path, method: :patch do |f| %>

	<div>
		<%= f.label :first_name, "First Name" %>
		<%= f.text_field :first_name %>

		<%= f.label :last_name, "Last Name" %>
		<%= f.text_field :last_name %>

		<%= f.label :email, "New Email Address" %>
		<%= f.text_field :email %>

		<%= f.label :password, "Password" %>
		<%= f.password_field :password %>
	</div>

	<br /><%= f.submit "Submit"%>
<% end %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/_guest_card.html.erb
<div class="profile-listing-box">
	<h2 class="listing-box-header">
		<%= link_to booking.user.full_name, user_path(booking.user.id)%> booked <%= link_to booking.listing.name, listing_path(booking.listing.id)%>, from <span class="underlined"><%=booking.start_date.to_date%></span> to <span class="underlined"><%=booking.end_date.to_date%></span>

		<span class="<%=booking.payment_status%>" style="float:right"><%=booking.payment_status%></span>
	</h2>
</div>

app/views/users/edit.html.erb
<% if (signed_in? && (current_user.id == @user.id)) %>
	<div class="container clearance-box centered w-25 p-0">
		<br />
		<h2 class="centered"><%=@user.full_name%></h2>
		<hr />

		<%= render 'edit_user_form', user: @user %>
		
	</div>
	<% else %>

	<h1 class="centered">You do not have permission to access this page</h1>

<% end %>

app/views/users/guests.html.erb
<h1 class="centered">Guests</h1>

<% if (signed_in? && current_user.id == @user.id) %>

<% if(@user_all_listings != nil) %>
	<% @user_all_listings.each do |listing| %>

		<% related_bookings = Booking.where(listing_id: listing.id).where("start_date > ?", Date.yesterday) %>

		<% related_bookings.order(:start_date).each do |booking| %>
			<%= render partial: "/users/guest_card", locals: {booking: booking} %>
		<% end %>

	<% end %>
<% else %>
	<h2 class="centered">Nothing here!</h2>
<% end %>

<% else %>

<h6 class="centered"> You are not allowed to view this page! #reported </h6>

<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container-fluid w-25 mt-5 form">
  <div class="row">
    <div class="col centered">

      <h2><%= t(".title") %></h2>
      <hr />

        <%= form_for :user, url: users_path do |f| %>
          <div class="input-group mb-2">
            <div class="input-group-prepend" data-toggle="tooltip" data-placement="left" title="First Name">
              <div class="input-group-text">
                <i class="fas fa-signature"></i>
              </div>
            </div>
            <%= f.text_field :first_name, :class => "form-control", :placeholder => "First Name" %>
          </div>

          <div class="input-group mb-2">
            <div class="input-group-prepend" data-toggle="tooltip" data-placement="left" title="Last Name">
              <div class="input-group-text">
                <i class="fas fa-signature"></i>
              </div>
            </div>
            <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name" %>
          </div>

          <div class="input-group mb-2">
            <div class="input-group-prepend" data-toggle="tooltip" data-placement="left" title="Email Address">
              <div class="input-group-text">
                <i class="fas fa-at"></i>
              </div>
            </div>
            <%= f.text_field :email, :class => "form-control", :placeholder => "Email Address" %>
          </div>

          <div class="input-group mb-2">
            <div class="input-group-prepend" data-toggle="tooltip" data-placement="left" title="Password">
              <div class="input-group-text">
                <i class="fas fa-key"></i>
              </div>
            </div>
            <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>
          </div>

          <div class="input-group mb-2">
            <div class="input-group-prepend" data-toggle="tooltip" data-placement="left" title="Avatar (optional)">
              <div class="input-group-text">
                <i class="fas fa-image"></i>
              </div>
            </div>
            <%= f.file_field :avatar_image, :class => "form-control" %>
          </div>


          <%= f.submit "Sign Up!", :class => "btn btn-primary w-100 mb-2"%>
        <% end %>
      <div>
        <%= link_to t(".sign_in"), sign_in_path, :class => "btn btn-secondary w-100" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="centered">

	<h1><%=@user.full_name%></h1>

	<%if (@user.avatar == nil) %>
		<%= image_tag "question-mark.jpg", class: "profile-page-avatar"%>
	<% else %>
		<%= image_tag @user.avatar.avatar_image.profile_size.url, class: "profile-page-avatar"%>
	<% end %>


	<br />
	<%="Member since #{@user.created_at.to_date}"%>
</div> <br /> <br />

<div class="centered">
	<%if(signed_in? && current_user.id != @user.id)%>
		<%= link_to "Chat!", chatrooms_path(@user.id), method: :post, class: "btn btn-success" %>
	<%end%>
</div>

<hr />
<table class="profile-details">
	<tr>
		<td class="profile-details-left">

			<%=show_role%>

			<%if signed_in? %>
				<%if current_user.moderator? || current_user.superadmin? %>
					<div class="moderator-profile-controls">
						<h2 class="underlined">Moderator Controls</h2>
						<ul class="no-bullets">
							<li>
								Add moderator commands for a user here
							</li>
						</ul>
					</div>
				<% end %>


				<%if (current_user_is(@user) || current_user.superadmin?) && (!current_user.moderator?) %>
					<h2 class="underlined">Controls</h2>
					<ul class="no-bullets">
						<li>
							<%= link_to "Add a Listing", new_listing_path%>
						</li>

						<li>
							<%= link_to "View my Bookings", bookings_path(@user.id) %>
						</li>

						<li>
							<%= link_to "View my Guests", guests_path(@user.id) %>
						</li>

						<li>
							<%= link_to "Edit my Profile", edit_user_path(@user.id) %>
						</li>

						<li>
							<%= link_to "Delete my Profile", "/users/#{@user.id}", :method => "DELETE"%>
						</li>
					</ul>
				<% else %>

				<% end %>
			<% end %>

			<h2 class="underlined">About</h2>
			<ul class="no-bullets">
				<li><%="Average Rating: #{@user.average_rating}/5"%></li>
				<li><%="Listings: #{@user.listings.length}"%></li>
			</ul>

		</td>
		<td>
			<%= render partial: "/listings/listing_card_profile", locals: {listings: @user.listings}%>
		</td>
	</tr>
</table>