config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  resources :chatrooms
  resources :messages
  # Root redirect
  root "welcome#index"

  # Clearance route overrides
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # Omniauth redirect
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

	# Resources from rails build
	resources :listing_photos
	resources :avatars
	resources :bookings
	resources :listings
	resources :users
  # resources :taggings NO NEEED RESOURCES TAGGING (NO TAGGING SHIT HAPPENING)
  # resources :tags NO NEED RESOURCES TAGS (NO TAG SHIT HAPPENING)

  # Manual additions
  # update user
  # make path for post to update
  patch "/users/:id" => "users#update", as: "update_user"

  # Verifying Listings
  put "/listings/verify/:id" => "listings#verify", as: "verify_listing"

  # Payments
  get '/payments/:booking_id' => "braintree#show", as: "payments"
  post 'braintree/checkout'

  # Guests
  get '/users/:id/guests' => "users#guests", as: "guests"

  #Searches
  # Filter search
  get '/search/show'

  # Text search
  get '/search/text_search'
  get '/search/text_search_ajax'

  # Mount channels for ActionCable
  mount ActionCable.server, at: '/cable'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@featured_listing = Listing.where("rating > ?", 3).sample
	end
	
end

app/views/welcome/index-backup.html.erb
<!--Hiding scrollbar for just this page-->
<style type="text/css">body{overflow: hidden}</style>

<div class="container-fluid" id="welcome">

		<div class="row no-gutters p-4 mx-auto">

			<div class="d-none d-xl-block col-8 p-4" id="random-listing-display">
				<h1>
					Random Listing: <%= link_to @featured_listing.name_with_verification_right, listing_path(@featured_listing)%>
					<span class="smoking"><%=@featured_listing.smoking_badge%></span>
				</h1>

				<h2>From <%= link_to @featured_listing.user.full_name, user_path(@featured_listing.user)%></h2>

				<ul id="random-listing-tags">
					<%@featured_listing.tags.each do |tag|%>
						<li><%=tag.text%> &nbsp;</li>
					<%end%>
				</ul>

				<div id="random-listing-stats">
					<%=@featured_listing.amenity_string%><br/>
					<div class="rating"><%=@featured_listing.symbolize_rating%></div>
					<%=@featured_listing.symbolize_capacity%>
				</div>

				<p>
					<br/>
					<%=@featured_listing.description.truncate(300)%>
				</p>
			</div>

			<div class="col" id="search-form-box">
				<div class="p-4">
					<h2 class="centered underlined">Find my NEXT home!</h2>

					<%=form_for :search, url: search_show_path, method: "GET" do |f|%>
						<br/>
						<table id="search-form">

							<tr>
								<td>
								Looking for a
								</td>
								<td><%=f.select :property_type, Listing::PROPERTY_TYPES%></td>

							</tr>

							<tr>
								<td>in</td>
								<td><%=f.select :country, ApplicationRecord::COUNTRIES%></td>

							</tr>

							<tr>
								<td>at most $</td>
								<td><%=f.text_field :max_price, :size => 4 %> a night</td>
							</tr>

						 	<tr>
						 		<td>with</td>
						 		<td><%=f.text_field :n_bedrooms, :size => 1%> bedroom(s)</td>
						 	</tr>

						 	<tr>
						 		<td>and</td>
						 		<td><%=f.text_field :n_bathrooms, :size => 1%> bathroom(s)</td>
						 	</tr>

						 	<tr>
						 		<td>Smoking?</td>
						 		<td><%=f.check_box :smoking_allowed%></td>
						 	</tr>

						 	<tr>
						 		<td colspan=2 style="text-align: left;">With the following amenities being a must:</td>
						 	</tr>
						</table>

						<table>
							<tr>
								<td>
									<%=f.label :essentials%><%=Listing.display_fa_icon(:essentials)%> <%=f.check_box :has_essentials%>
								</td>

						        <td>
						        	<%=f.label :airconditioner%><%=Listing.display_fa_icon(:airconditioner)%> <%=f.check_box :has_airconditioner%>
						        </td>

						        <td>
						        	<%=f.label :laundry%><%=Listing.display_fa_icon(:washer_dryer)%> <%=f.check_box :has_washer_dryer%>
						        </td>

						        <td>
						        	<%=f.label :television%><%=Listing.display_fa_icon(:television)%> <%=f.check_box :has_television%>
						        </td>

						        <td>
						        	<%=f.label :fireplace%><%=Listing.display_fa_icon(:fireplace)%> <%=f.check_box :has_fireplace%>
						        </td>
							</tr>
							<tr>
						        <td>
						        	<%=f.label :wifi%><%=Listing.display_fa_icon(:wifi)%> <%=f.check_box :has_wifi%>
						        </td>

						        <td>
						        	<%=f.label :hot_water%><%=Listing.display_fa_icon(:hot_water)%> <%=f.check_box :has_hot_water%>
						        </td>

						        <td>
						        	<%=f.label :kitchen%><%=Listing.display_fa_icon(:kitchen)%> <%=f.check_box :has_kitchen%>
						        </td>

						        <td>
						        	<%=f.label :heating%><%=Listing.display_fa_icon(:heating)%> <%=f.check_box :has_heating%>
						        </td>

						        <td>
						        	<%=f.label :living_room%><%=Listing.display_fa_icon(:living_room)%> <%=f.check_box :has_living_room%>
						        </td>
							</tr>

							<tr>
								<td colspan=5 class=centered><%=f.submit "Search!"%></td>
							</tr>
						</table>

					<% end %>

					<hr />

					<h3 class="centered">Alternatively, use our text search...</h3>
					<div class="centered">

						<form action='/search/text_search' method="GET">
							<input type="text" list="list" id="text-search" name="text_search[keywords]"/>

							<input type="submit" value=">"/>


							<datalist id="list">
							</datalist>
						</form>
						<br />
					</div>
				</div>
			</div>

		</div>

</div>

<!-- AJAX SHIT -->
<script>
		let search_box = document.getElementById("text-search")

		if(search_box)	{search_box.addEventListener("keyup", function(event) 	{autocomplete(event)})}


		function autocomplete(event)	{
			let xhttp = new XMLHttpRequest()
			let input = event.target
			let list = document.getElementById("list")

			if(input.value.length > 0)	{
				xhttp.abort()

				xhttp.onreadystatechange = function()	{
					if (this.readyState == 4 && this.status == 200)	{
						let response = JSON.parse(this.responseText)
						// console.log(this.responseText[0])

						list.innerHTML = ""

						response.forEach(function(element)	{
							let option = document.createElement("option")
							option.value = element["name"]
							option.innerHTML = element["city"]

							list.appendChild(option)
						})

					}
				}

			    let auth_token = document.querySelector("[name='csrf-token']").content
			    xhttp.open("GET", "/search/text_search_ajax?text_search[keywords]=" + input.value, true)
			    xhttp.send()
			}
		}
</script>

app/views/welcome/index.html.erb
<!--Hiding scrollbar for just this page-->
<style type="text/css">body{overflow: hidden}</style>

<div class="container-fluid" id="welcome">

	<div class="row no-gutters p-5 mx-auto">

		<div class="d-none d-xl-block col-8 p-4" id="random-listing-display">
			<h1>
				Random Listing: <%= link_to @featured_listing.name_with_verification_right, listing_path(@featured_listing)%>
				<span class="smoking"><%=@featured_listing.smoking_badge%></span>
			</h1>

			<h2>From <%= link_to @featured_listing.user.full_name, user_path(@featured_listing.user)%></h2>

			<ul id="random-listing-tags">
				<%@featured_listing.tags.each do |tag|%>
					<li><%=tag.text%> &nbsp;</li>
				<%end%>
			</ul>
			
			<div id="random-listing-stats">
				<%=@featured_listing.amenity_string%><br/>
				<div class="rating"><%=@featured_listing.symbolize_rating%></div>
				<%=@featured_listing.symbolize_capacity%>
			</div>
		
			<p>
				<br/>
				<%=@featured_listing.description.truncate(300)%>
			</p>
		</div>

		<div class="col p-4" id="search-form-box">
			<%=form_for :search, url: search_show_path, method: "GET" do |f|%>
				
				<div class="input-group mt-2">
					<div class="input-group-prepend" data-toggle="tooltip" title="Listing Type" data-placement="left">
						<span class="input-group-text"><i class="fas fa-building"></i></span>
					</div>
						<%=f.select :property_type, Listing::PROPERTY_TYPES, {}, {:class => "form-control"}%>
				</div>

				<div class="input-group mt-2">
					<div class="input-group-prepend" data-toggle="tooltip" title="Country" data-placement="left">
						<div class="input-group-text"><i class="fas fa-globe"></i></div>
					</div>
					<%=f.select :country, ApplicationRecord::COUNTRIES, {}, {:class => "form-control w-75"}%>
				</div>

				<div class="row">
					<div class="col-4">
						<div class="input-group mt-2">
							<div class="input-group-prepend" data-toggle="tooltip" title="Price per Night ($)" data-placement="top">
								<div class="input-group-text"><i class="fas fa-money-bill"></i></div>
							</div>
							<%=f.text_field :max_price, :size => 4, :class => "form-control"%>		
						</div>
					</div>
					<div class="col-4">
						<div class="input-group mt-2">
							<div class="input-group-prepend" data-toggle="tooltip" title="Bathrooms" data-placement="top">
								<div class="input-group-text"><i class="fas fa-toilet-paper"></i></div>
							</div>
							<%=f.text_field :n_bathrooms, :size => 4, :class => "form-control"%>
						</div>
					</div>
					<div class="col-4">
						<div class="input-group mt-2">
							<div class="input-group-prepend" data-toggle="tooltip" title="Bedrooms" data-placement="top">
								<div class="input-group-text"><i class="fas fa-bed"></i></div>
							</div>
							<%=f.text_field :n_bedrooms, :size => 4, :class => "form-control"%>
						</div>
					</div>
				</div>

		<!-- AMENITITES WORK -->
				<div class="row my-4">
					<% i = 0 %>
					<% Listing::AMENITIES.each do |key, value|%>
						<div class="col-2 my-2">
							<%=f.check_box "has_#{key}".to_sym, :id => i, :class => "hidden-checkbox"%>
							<label for="<%=i%>" class="label-for-check" data-toggle="tooltip" title="<%="#{key.to_s.capitalize.split("_").join(" ")}"%>" data-placement="top">
								<%=Listing.display_fa_icon(key)%>
							</label>
						</div>

						<% i += 1 %>
					<% end %>
				</div>
			
		<!-- END AMENITIES WORK -->

				<%=f.check_box :smoking_allowed, :class => "hidden-checkbox", :id => "smoking_allowed"%>
				<label for="smoking_allowed" id="smoking_allowed_label" class="label-for-check-smoking" data-toggle="tooltip" title="Allowed to Smoke?" data-placement="top">
					<span class="text-white">SMOKING</span><i class="fas fa-smoking-ban"></i><span class="text-white">ALLOWED</span>
				</label>
				<div class="input-group mt-2">
					<%=f.submit "Find My NEXT Home", :class => "btn btn-primary w-100"%>
				</div>

					
			<% end %>

			<hr />
			
			<div class="centered mt-3">
				<form action='/search/text_search' method="GET">
					<div class="input-group">
						<input type="text" list="list" id="text-search" name="text_search[keywords]" class="form-control" placeholder="Enter keywords..." />

						<span class="btn-group input-group-append" role="group" aria-label="Search Buttons">
							<button type="submit" class="btn btn-primary">
								<i class="fas fa-search"></i>
							</button>
							<button type="reset" class="btn">
								<i class="fas fa-eraser"></i>
							</button>
						</span>
					</div>
					<datalist id="list"></datalist>
				</form>

			</div>
		</div>
	</div>	
</div>

<!-- AJAX SHIT -->
<script>
		let search_box = document.getElementById("text-search")

		if(search_box)	{search_box.addEventListener("keyup", function(event) 	{autocomplete(event)})}


		function autocomplete(event)	{
			let xhttp = new XMLHttpRequest()
			let input = event.target
			let list = document.getElementById("list")

			if(input.value.length > 0)	{
				xhttp.abort()

				xhttp.onreadystatechange = function()	{
					if (this.readyState == 4 && this.status == 200)	{
						let response = JSON.parse(this.responseText)
						// console.log(this.responseText[0])

						list.innerHTML = ""

						response.forEach(function(element)	{
							let option = document.createElement("option")
							option.value = element["name"]
							option.innerHTML = element["city"]

							list.appendChild(option)
						})

					}
				}

			    let auth_token = document.querySelector("[name='csrf-token']").content
			    xhttp.open("GET", "/search/text_search_ajax?text_search[keywords]=" + input.value, true)
			    xhttp.send()
			}
		}
</script>

app/views/welcome/snippet.html.erb
						<div>
							<h1>Random Listing: <%= link_to @featured_listing.name_with_verification_right, listing_path(@featured_listing)%><%=@featured_listing.smoking_badge%></h1>
							<h2>From <%= link_to @featured_listing.user.full_name, user_path(@featured_listing.user)%></h2>
							<%=@featured_listing.amenity_string%><br/>
							<%=@featured_listing.symbolize_rating%><br/>
							<%=@featured_listing.symbolize_capacity%>


							<ul style="font-size: 14pt; line-height: 2em;">
								<%@featured_listing.tags.each do |tag|%>
									<li><%=tag.text%></li>
								<%end%>
							</ul>

							<h2><%=@featured_listing.description.truncate(300)%></h2>

						</div>





						!-!!!!!


						<div>
							<h2 class="centered underlined">Find my NEXT home!</h2>

							<%=form_for :search, url: search_show_path, method: "GET" do |f|%>
								<br/>
								<table id="search-form">

									<tr>
										<td>
										Looking for a
										</td>
										<td><%=f.select :property_type, Listing::PROPERTY_TYPES%></td>

									</tr>

									<tr>
										<td>in</td>
										<td><%=f.select :country, ApplicationRecord::COUNTRIES%></td>

									</tr>

									<tr>
										<td>at most $</td>
										<td><%=f.text_field :max_price, :size => 4 %> a night</td>
									</tr>

								 	<tr>
								 		<td>with</td>
								 		<td><%=f.text_field :n_bedrooms, :size => 1%> bedroom(s)</td>
								 	</tr>

								 	<tr>
								 		<td>and</td>
								 		<td><%=f.text_field :n_bathrooms, :size => 1%> bathroom(s)</td>
								 	</tr>

								 	<tr>
								 		<td>Smoking?</td>
								 		<td><%=f.check_box :smoking_allowed%></td>
								 	</tr>

								 	<tr>
								 		<td colspan=2 style="text-align: left;">With the following amenities being a must:</td>
								 	</tr>
								</table>

								<table>
									<tr>
										<td><%=f.label :essentials%><%="#{Listing::AMENITIES[:essentials]}"%> <%=f.check_box :has_essentials%></td>

								        <td><%=f.label :airconditioner%><%="#{Listing::AMENITIES[:airconditioner]}"%> <%=f.check_box :has_airconditioner%></td>

								        <td><%=f.label :washer_dryer%><%="#{Listing::AMENITIES[:washer_dryer]}"%> <%=f.check_box :has_washer_dryer%></td>

								        <td><%=f.label :television%><%="#{Listing::AMENITIES[:television]}"%> <%=f.check_box :has_television%></td>

								        <td><%=f.label :fireplace%><%="#{Listing::AMENITIES[:fireplace]}"%> <%=f.check_box :has_fireplace%></td>
									</tr>
									<tr>
								        <td><%=f.label :wifi%><%="#{Listing::AMENITIES[:wifi]}"%> <%=f.check_box :has_wifi%></td>

								        <td><%=f.label :hot_water%><%="#{Listing::AMENITIES[:hot_water]}"%> <%=f.check_box :has_hot_water%></td>

								        <td><%=f.label :kitchen%><%="#{Listing::AMENITIES[:kitchen]}"%> <%=f.check_box :has_kitchen%></td>

								        <td><%=f.label :heating%><%="#{Listing::AMENITIES[:heating]}"%> <%=f.check_box :has_heating%></td>

								        <td><%=f.label :living_room%><%="#{Listing::AMENITIES[:living_room]}"%> <%=f.check_box :has_living_room%></td>
									</tr>

									<tr>
										<td colspan=5 class=centered><%=f.submit "Search!"%></td>
									</tr>
								</table>

							<% end %>

							<hr />

							<h3 class="centered">Alternatively, use our text search...</h3>
							<div class="centered">

								<form action='/search/text_search' method="GET">
									<input type="text" list="list" id="text-search" name="text_search[keywords]"/>

									<input type="submit" value=">"/>


									<datalist id="list">
									</datalist>
								</form>
								<br />

							</div>
						</div>

app/views/welcome/snippet_search.html.erb
<br/>
						<table id="search-form">

							<tr>
								<td>
								Looking for a
								</td>
								<td><%=f.select :property_type, Listing::PROPERTY_TYPES%></td>

							</tr>

							<tr>
								<td>in</td>
								<td><%=f.select :country, ApplicationRecord::COUNTRIES%></td>

							</tr>

							<tr>
								<td>at most $</td>
								<td><%=f.text_field :max_price, :size => 4 %> a night</td>
							</tr>

						 	<tr>
						 		<td>with</td>
						 		<td><%=f.text_field :n_bedrooms, :size => 1%> bedroom(s)</td>
						 	</tr>

						 	<tr>
						 		<td>and</td>
						 		<td><%=f.text_field :n_bathrooms, :size => 1%> bathroom(s)</td>
						 	</tr>

						 	<tr>
						 		<td>Smoking?</td>
						 		<td><%=f.check_box :smoking_allowed%></td>
						 	</tr>

						 	<tr>
						 		<td colspan=2 style="text-align: left;">With the following amenities being a must:</td>
						 	</tr>
						</table>

						<table>
							<tr>
								<td>
									<%=f.label :essentials%><%=Listing.display_fa_icon(:essentials)%> <%=f.check_box :has_essentials%>
								</td>

						        <td>
						        	<%=f.label :airconditioner%><%=Listing.display_fa_icon(:airconditioner)%> <%=f.check_box :has_airconditioner%>
						        </td>

						        <td>
						        	<%=f.label :laundry%><%=Listing.display_fa_icon(:washer_dryer)%> <%=f.check_box :has_washer_dryer%>
						        </td>

						        <td>
						        	<%=f.label :television%><%=Listing.display_fa_icon(:television)%> <%=f.check_box :has_television%>
						        </td>

						        <td>
						        	<%=f.label :fireplace%><%=Listing.display_fa_icon(:fireplace)%> <%=f.check_box :has_fireplace%>
						        </td>
							</tr>
							<tr>
						        <td>
						        	<%=f.label :wifi%><%=Listing.display_fa_icon(:wifi)%> <%=f.check_box :has_wifi%>
						        </td>

						        <td>
						        	<%=f.label :hot_water%><%=Listing.display_fa_icon(:hot_water)%> <%=f.check_box :has_hot_water%>
						        </td>

						        <td>
						        	<%=f.label :kitchen%><%=Listing.display_fa_icon(:kitchen)%> <%=f.check_box :has_kitchen%>
						        </td>

						        <td>
						        	<%=f.label :heating%><%=Listing.display_fa_icon(:heating)%> <%=f.check_box :has_heating%>
						        </td>

						        <td>
						        	<%=f.label :living_room%><%=Listing.display_fa_icon(:living_room)%> <%=f.check_box :has_living_room%>
						        </td>
							</tr>

							<tr>
								<td colspan=5 class=centered><%=f.submit "Search!"%></td>
							</tr>
						</table>